language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer install --no-interaction
  - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard

script:
  - find src -type f -name '*.php' |xargs -I file php -l file
  - vendor/bin/phpcs -p --extensions=php --standard=Symfony2 src
